#Example
version: "2"

linters:
  default: none
  enable:
    - loglint  
  settings:
    custom:
      loglint:
        type: "module"
        description: This is an standart message logs usage of a plugin linter.
        original-url: "https://github.com/LainIwakuras-father/slogzaplint"
        settings:
          enabled-rules:
            - lowercase
            - english
            - no-special'
            - no-sensitive
          sensitive-patterns:
            - "api_key"
            - "password"
            - "token"


